[package]
name = "unit-derive"
version = "0.1.0"
authors = ["Paul Ellenbogen <pe5@cs.princeton.edu>"]
description = "Derive ops for newtype units in Rust."
license = "MIT"

[dependencies]
syn = "0.10.5"
quote = "0.3.10"

[lib]
proc-macro = true